name: Pull-Requests Images

env:
  LABEL_NAME: "test_publish"
  WORKFLOW_CI_FN: "ci.yaml"
  GITHUB_TOKEN: ${{ github.token }}
  GITHUB_PR_ID: ${{github.event.number}}
  GITHUB_EVENT_ACTION: ${{github.event.action}}
  GITHUB_OWNER_TYPE: ${{github.event.repository.owner.type == 'User' && 'user' || 'org'}}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{github.event.number}}

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    name: Inspect
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: read
      actions: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: |
            go.sum

      - name: Execute
        id: refs
        run: |
          set -ex
          
          function hasLabel() {
            go run ./build has-pr-label "${GITHUB_PR_ID}" "${LABEL_NAME}" && return 0 || retVal=$?
            if [ "$retVal" -eq 1 ]; then
              return 1
            fi
            exit $retVal
          }
          
          function isOpen() {
            go run ./build is-pr-open "${GITHUB_PR_ID}" && return 0 || retVal=$?
            if [ "$retVal" -eq 1 ]; then
              return 1
            fi
            exit $retVal
          }
          
          function triggerCiWorkflow() {
            go run ./build rerun-pr-workflow "${GITHUB_PR_ID}" "${WORKFLOW_CI_FN}"
          }
          
          function removeImages() {
            go run ./build delete-image-tag "pr-${GITHUB_PR_ID}"
          }
          
          if [ "$GITHUB_EVENT_ACTION" == "labeled" ]; then
            if [ "${{github.event.label.name}}" == "${LABEL_NAME}" ] && isOpen; then
              triggerCiWorkflow
            fi
          
          elif [ "$GITHUB_EVENT_ACTION" == "unlabeled" ]; then
            if [ "${{github.event.label.name}}" == "${LABEL_NAME}" ] && isOpen; then
              removeImages
            fi
          
          elif [ "$GITHUB_EVENT_ACTION" == "closed" ]; then
            if hasLabel; then
              removeImages
            fi
          
          fi
